-- B12 Steak menu variants: Tek / Duble / Şişe, 250ML / 750ML vb.
create table if not exists public.menu_item_variants (
 id bigint generated by default as identity primary key,
 item_id bigint not null references public.menu_items(id) on delete cascade,
 label_tr text not null,
 label_en text,
 price numeric(10,2) not null default 0,
 sort_order integer not null default 0,
 is_active boolean not null default true
);
alter table public.menu_item_variants enable row level security;
create index if not exists idx_menu_item_variants_item on public.menu_item_variants(item_id);
create policy "Public can read active variants" on public.menu_item_variants for select to anon,authenticated using(is_active=true);
create policy "Admins can read all variants" on public.menu_item_variants for select to authenticated using(public.is_menu_admin());
create policy "Admins can insert variants" on public.menu_item_variants for insert to authenticated with check(public.is_menu_admin());
create policy "Admins can update variants" on public.menu_item_variants for update to authenticated using(public.is_menu_admin()) with check(public.is_menu_admin());
create policy "Admins can delete variants" on public.menu_item_variants for delete to authenticated using(public.is_menu_admin());
grant select on public.menu_item_variants to anon,authenticated;
grant insert,update,delete on public.menu_item_variants to authenticated;
grant usage,select on all sequences in schema public to authenticated;
