"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createServerSupabase} from "../../lib/supabase/server";
async function adminDb(){const db=await createServerSupabase();const{data:{user}}=await db.auth.getUser();if(!user)redirect("/admin/login");const{data:a}=await db.from("admin_users").select("role").eq("user_id",user.id).maybeSingle();if(!a)redirect("/admin/login");return db}
function refresh(){["/admin","/menu","/en/menu","/ru/menu"].forEach(revalidatePath)}
export async function saveItem(form:FormData){const db=await adminDb();const id=String(form.get("id")||"");const row={section_id:Number(form.get("section_id")),name_tr:String(form.get("name_tr")||""),name_en:String(form.get("name_en")||"")||null,name_ru:String(form.get("name_ru")||"")||null,description_tr:String(form.get("description_tr")||"")||null,description_en:String(form.get("description_en")||"")||null,description_ru:String(form.get("description_ru")||"")||null,price:Number(form.get("price")||0),is_active:form.get("is_active")==="on"};if(id)await db.from("menu_items").update(row).eq("id",Number(id));else await db.from("menu_items").insert(row);refresh()}
export async function deleteItem(form:FormData){const db=await adminDb();await db.from("menu_items").delete().eq("id",Number(form.get("id")));refresh()}
export async function saveVariant(form:FormData){const db=await adminDb();const id=String(form.get("variant_id")||"");const row={item_id:Number(form.get("item_id")),label_tr:String(form.get("label_tr")||""),label_en:String(form.get("label_en")||"")||null,label_ru:String(form.get("label_ru")||"")||null,price:Number(form.get("variant_price")||0),is_active:form.get("variant_active")==="on"};if(id)await db.from("menu_item_variants").update(row).eq("id",Number(id));else await db.from("menu_item_variants").insert(row);refresh()}
export async function deleteVariant(form:FormData){const db=await adminDb();await db.from("menu_item_variants").delete().eq("id",Number(form.get("variant_id")));refresh()}
export async function uploadImage(form:FormData){const db=await adminDb();const itemId=Number(form.get("item_id"));const file=form.get("image") as File;if(!file||!file.size)return;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path="items/"+itemId+"-"+Date.now()+"."+ext;const{error}=await db.storage.from("menu-images").upload(path,file,{upsert:true,contentType:file.type});if(!error)await db.from("menu_items").update({image_path:path}).eq("id",itemId);refresh()}
export async function logout(){const db=await createServerSupabase();await db.auth.signOut();redirect("/admin/login")}
