"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createServerSupabase} from "../../lib/supabase/server";
async function adminDb(){const db=await createServerSupabase();const{data:{user}}=await db.auth.getUser();if(!user)redirect("/admin/login");const{data:a}=await db.from("admin_users").select("role").eq("user_id",user.id).maybeSingle();if(!a)redirect("/admin/login");return db}
function refresh(){revalidatePath("/admin");revalidatePath("/menu");revalidatePath("/en/menu");revalidatePath("/ru/menu")}
export async function saveCategory(form:FormData){const db=await adminDb();const id=String(form.get("category_id")||"");const row={slug:String(form.get("slug")||"").trim().toLowerCase().replace(/\s+/g,"-"),title_tr:String(form.get("title_tr")||""),title_en:String(form.get("title_en")||"")||null,title_ru:String(form.get("title_ru")||"")||null,sort_order:Number(form.get("sort_order")||0),is_active:form.get("category_active")==="on"};if(id)await db.from("menu_categories").update(row).eq("id",Number(id));else await db.from("menu_categories").insert(row);refresh()}
export async function deleteCategory(form:FormData){const db=await adminDb();const id=Number(form.get("category_id"));const{count}=await db.from("menu_sections").select("id",{count:"exact",head:true}).eq("category_id",id);if((count||0)>0)throw new Error("Bu kategoride alt bölümler var. Önce alt bölümleri taşıyın veya silin.");const{error}=await db.from("menu_categories").delete().eq("id",id);if(error)throw new Error(error.message);refresh()}
export async function saveSection(form:FormData){const db=await adminDb();const id=String(form.get("section_id_edit")||"");const row={category_id:Number(form.get("category_id")),title_tr:String(form.get("title_tr")||""),title_en:String(form.get("title_en")||"")||null,title_ru:String(form.get("title_ru")||"")||null,sort_order:Number(form.get("sort_order")||0),is_active:form.get("section_active")==="on"};if(id)await db.from("menu_sections").update(row).eq("id",Number(id));else await db.from("menu_sections").insert(row);refresh()}
export async function deleteSection(form:FormData){const db=await adminDb();const id=Number(form.get("section_id_edit"));const{count}=await db.from("menu_items").select("id",{count:"exact",head:true}).eq("section_id",id);if((count||0)>0)throw new Error("Bu bölümde ürünler var. Önce ürünleri başka bölüme taşıyın veya silin.");const{error}=await db.from("menu_sections").delete().eq("id",id);if(error)throw new Error(error.message);refresh()}
export async function saveItem(form:FormData){const db=await adminDb();const id=String(form.get("id")||"");const row={section_id:Number(form.get("section_id")),name_tr:String(form.get("name_tr")||""),name_en:String(form.get("name_en")||"")||null,name_ru:String(form.get("name_ru")||"")||null,description_tr:String(form.get("description_tr")||"")||null,description_en:String(form.get("description_en")||"")||null,description_ru:String(form.get("description_ru")||"")||null,price:Number(form.get("price")||0),tags:String(form.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),sort_order:Number(form.get("sort_order")||0),is_active:form.get("is_active")==="on"};const{error}=id?await db.from("menu_items").update(row).eq("id",Number(id)):await db.from("menu_items").insert(row);if(error)throw new Error(error.message);refresh()}
export async function deleteItem(form:FormData){const db=await adminDb();const{error}=await db.from("menu_items").delete().eq("id",Number(form.get("id")));if(error)throw new Error(error.message);refresh()}
export async function saveVariant(form:FormData){const db=await adminDb();const id=String(form.get("variant_id")||"");const row={item_id:Number(form.get("item_id")),label_tr:String(form.get("label_tr")||""),label_en:String(form.get("label_en")||"")||null,label_ru:String(form.get("label_ru")||"")||null,price:Number(form.get("variant_price")||0),sort_order:Number(form.get("variant_sort_order")||0),is_active:form.get("variant_active")==="on"};const{error}=id?await db.from("menu_item_variants").update(row).eq("id",Number(id)):await db.from("menu_item_variants").insert(row);if(error)throw new Error(error.message);refresh()}
export async function deleteVariant(form:FormData){const db=await adminDb();const{error}=await db.from("menu_item_variants").delete().eq("id",Number(form.get("variant_id")));if(error)throw new Error(error.message);refresh()}
export async function uploadImage(form:FormData){const db=await adminDb();const itemId=Number(form.get("item_id"));const file=form.get("image") as File;if(!file||!file.size)return;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path="items/"+itemId+"-"+Date.now()+"."+ext;const allowed=["image/jpeg","image/png","image/webp","image/avif"];if(!allowed.includes(file.type))throw new Error("Yalnız JPG, PNG, WEBP veya AVIF görsel yükleyebilirsiniz.");if(file.size>5*1024*1024)throw new Error("Görsel en fazla 5 MB olabilir.");const{error}=await db.storage.from("menu-images").upload(path,file,{upsert:true,contentType:file.type});if(error)throw new Error(error.message);const{error:updateError}=await db.from("menu_items").update({image_path:path}).eq("id",itemId);if(updateError)throw new Error(updateError.message);refresh()}
export async function logout(){const db=await createServerSupabase();await db.auth.signOut();redirect("/admin/login")}
