import {createServerSupabase} from "../../../lib/supabase/server";export const dynamic="force-dynamic";type C={id:number;slug:string;title_tr:string;title_en:string|null;title_ru:string|null};type S={id:number;category_id:number;title_tr:string;title_en:string|null;title_ru:string|null};type I={id:number;section_id:number;name_tr:string;name_en:string|null;name_ru:string|null;description_tr:string|null;description_en:string|null;description_ru:string|null;price:number;tags:string[];image_path:string|null};type V={id:number;item_id:number;label_tr:string;label_en:string|null;label_ru:string|null;price:number};const localImage=(name:string)=>{
 const n=name.toLocaleLowerCase("tr-TR").trim();
 const images:Record<string,string>={
  "peynir tabağı":"/images/menu/baslangic/peynir-taba─ş─▒.webp","şarküteri tabağı":"/images/menu/baslangic/┼şarkuteri-taba─ş─▒.webp","dana carpaccio":"/images/menu/baslangic/danakarpa├ğyo.webp","steak tartar":"/images/menu/baslangic/Steak-tartar.webp",
  "domates":"/images/menu/salatalar/Domates-salatas─▒.webp","roka":"/images/menu/salatalar/Roka-Salatas─▒.webp","akdeniz":"/images/menu/salatalar/Akdenizsalata.webp","tulum":"/images/menu/salatalar/tulumsalata.webp","steak salata":"/images/menu/salatalar/Steak-salata.webp",
  "dallas":"/images/menu/ana-yemek/dry-aged/Dallas.webp","t-bone":"/images/menu/ana-yemek/dry-aged/T-BONE.webp","new-york":"/images/menu/ana-yemek/dry-aged/newyork.webp","ribeye":"/images/menu/ana-yemek/dry-aged/ribeye.webp",
  "takoz bonfile":"/images/menu/ana-yemek/beef/Takoz-Bonfile.webp","bonfile lokum":"/images/menu/ana-yemek/beef/Bonfile-Lokum.webp","şaşlık":"/images/menu/ana-yemek/beef/┼Şa┼şl─▒k.webp","yaprak antrikot":"/images/menu/ana-yemek/beef/yaprakantikot.webp","kuzu pirzola":"/images/menu/ana-yemek/beef/Kuzu-Pirzola.webp","kuzu küşleme":"/images/menu/ana-yemek/beef/Kuzu-K├╝┼şleme.webp","kuzu sırt (karski)":"/images/menu/ana-yemek/beef/karski.webp","kuzu kafes":"/images/menu/ana-yemek/beef/Kuzu-Kafes.webp","dilim asado":"/images/menu/ana-yemek/beef/dana-asado.webp","file şato beef 4 kişilik":"/images/menu/ana-yemek/beef/satobiryan.webp","file şato beef 2 kişilik":"/images/menu/ana-yemek/beef/satobiryan.webp",
  "cheddar köfte":"/images/menu/kofte/cheddar-k├Âfte.webp","cheese burger":"/images/menu/burger/chesse-burger.webp","lokum burger":"/images/menu/burger/Lokum-Dana-Burger.webp","solo 1":"/images/menu/solo/Solo1.webp","solo 2":"/images/menu/solo/solo2.webp","s.pellegrino":"/images/menu/soft/St.Pellegrino.webp","soda":"/images/menu/soft/Soda.webp","uludağ soda":"/images/menu/soft/uludag.webp","tiramisu":"/images/menu/tatli/Tiramisu.webp"
 };return images[n]||null;
};
const itemImage=(i:I)=>i.image_path?process.env.NEXT_PUBLIC_SUPABASE_URL+"/storage/v1/object/public/menu-images/"+i.image_path:localImage(i.name_tr);
const money=(v:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(v));export default async function Page({searchParams}:{searchParams:Promise<{menu?:string}>}){const q=await searchParams,db=await createServerSupabase();const [{data:cs},{data:ss},{data:ii},{data:vv}]=await Promise.all([db.from("menu_categories").select("*").eq("is_active",true).order("sort_order"),db.from("menu_sections").select("*").eq("is_active",true).order("sort_order"),db.from("menu_items").select("*").eq("is_active",true).order("sort_order"),db.from("menu_item_variants").select("*").eq("is_active",true).order("sort_order")]);const cats=(cs||[]) as C[],active=cats.find(c=>c.slug===q.menu)||cats[0],secs=((ss||[]) as S[]).filter(s=>s.category_id===active?.id),items=(ii||[]) as I[],vars=(vv||[]) as V[],pick=(o:any,k:string)=>o[k+"_ru"]||o[k+"_tr"];return <main className="menuPage"><section className="menuTop"><h1>Меню</h1><nav className="menuTabs">{cats.map(c=><a className={active?.id===c.id?"active":""} href={"/ru/menu?menu="+c.slug} key={c.id}>{pick(c,"title")}</a>)}</nav></section><section className="wixMenu"><h2 className="menuCategoryTitle">{active&&pick(active,"title")}</h2>{secs.map(s=><section className="menuSection" key={s.id}><h2>{pick(s,"title")}</h2><div className="sectionRule"/>{items.filter(i=>i.section_id===s.id).map(i=>{const vs=vars.filter(v=>v.item_id===i.id);return <article className="dish" key={i.id}><div className="dishCopy">{itemImage(i)&&<img className="menuItemImage" src={itemImage(i)!} alt={pick(i,"name")}/>}<h3>{pick(i,"name")}</h3>{pick(i,"description")&&<p>{pick(i,"description")}</p>}{i.tags?.length>0&&<p className="dishTags">{i.tags.join(" · ")}</p>}</div><div className="dishPrice">{vs.length?vs.map(v=><div className="variant" key={v.id}><span>{pick(v,"label")}</span><strong>{money(v.price)}</strong></div>):<strong>{money(i.price)}</strong>}</div></article>})}</section>)}</section></main>}