import {createServerSupabase} from "../../../lib/supabase/server";export const dynamic="force-dynamic";type C={id:number;slug:string;title_tr:string;title_en:string|null;title_ru:string|null};type S={id:number;category_id:number;title_tr:string;title_en:string|null;title_ru:string|null};type I={id:number;section_id:number;name_tr:string;name_en:string|null;name_ru:string|null;description_tr:string|null;description_en:string|null;description_ru:string|null;price:number;tags:string[];image_path:string|null};type V={id:number;item_id:number;label_tr:string;label_en:string|null;label_ru:string|null;price:number};const imageKey=(value:string)=>value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll("ı","i").replaceAll("ş","s").replaceAll("ğ","g").replaceAll("ü","u").replaceAll("ö","o").replaceAll("ç","c").trim();
const localImage=(name:string)=>{
 const n=imageKey(name);
 const images:Record<string,string>={
  "peynir tabağı":"/images/menu/baslangic/peynir-taba─ş─▒.webp","şarküteri tabağı":"/images/menu/baslangic/┼şarkuteri-taba─ş─▒.webp","dana carpaccio":"/images/menu/baslangic/danakarpa├ğyo.webp","steak tartar":"/images/menu/baslangic/Steak-tartar.webp",
  "domates":"/images/menu/salatalar/Domates-salatas─▒.webp","roka":"/images/menu/salatalar/Roka-Salatas─▒.webp","akdeniz":"/images/menu/salatalar/Akdenizsalata.webp","tulum":"/images/menu/salatalar/tulumsalata.webp","steak salata":"/images/menu/salatalar/Steak-salata.webp",
  "domates salatasi":"/images/menu/salatalar/Domates-salatas─▒.webp",
  "roka salatasi":"/images/menu/salatalar/Roka-Salatas─▒.webp",
  "akdeniz salatasi":"/images/menu/salatalar/Akdenizsalata.webp",
  "tulum salatasi":"/images/menu/salatalar/tulumsalata.webp",
  "dallas":"/images/menu/ana-yemek/dry-aged/Dallas.webp","t-bone":"/images/menu/ana-yemek/dry-aged/T-BONE.webp","new-york":"/images/menu/ana-yemek/dry-aged/newyork.webp","ribeye":"/images/menu/ana-yemek/dry-aged/ribeye.webp",
  "takoz bonfile":"/images/menu/ana-yemek/beef/Takoz-Bonfile.webp","bonfile lokum":"/images/menu/ana-yemek/beef/Bonfile-Lokum.webp","şaşlık":"/images/menu/ana-yemek/beef/┼Şa┼şl─▒k.webp","yaprak antrikot":"/images/menu/ana-yemek/beef/yaprakantikot.webp","kuzu pirzola":"/images/menu/ana-yemek/beef/Kuzu-Pirzola.webp","kuzu küşleme":"/images/menu/ana-yemek/beef/Kuzu-K├╝┼şleme.webp","kuzu sırt (karski)":"/images/menu/ana-yemek/beef/karski.webp","kuzu kafes":"/images/menu/ana-yemek/beef/Kuzu-Kafes.webp","dilim asado":"/images/menu/ana-yemek/beef/dana-asado.webp","demi glace bonfile":"/images/menu/ana-yemek/beef/Takoz-Bonfile-edited.webp",
  "file şato beef 4 kişilik":"https://static.wixstatic.com/media/5f9784_8e61a326b2924697b4b6a04756fce2a5~mv2.jpg","file şato beef 2 kişilik":"https://static.wixstatic.com/media/5f9784_8e61a326b2924697b4b6a04756fce2a5~mv2.jpg",
  "cheddar köfte":"/images/menu/kofte/cheddar-k├Âfte-edited.webp","cheese burger":"/images/menu/burger/chesse-burger.webp",
  "mexican burger":"/images/menu/burger/chesse-burger.webp",
  "bacon cheese burger":"/images/menu/burger/chesse-burger.webp","lokum burger":"/images/menu/burger/Lokum-Dana-Burger.webp","solo 1":"/images/menu/solo/Solo1.webp","solo 2":"/images/menu/solo/solo2.webp","su":"https://static.wixstatic.com/media/5f9784_64ea26890dd54416802da3156e4122f2~mv2.png",
"şalgam suyu 330 ml":"https://static.wixstatic.com/media/5f9784_798c0614a3834d0f8106807c46a754cd~mv2.png",
"ayran":"https://static.wixstatic.com/media/5f9784_3d00b47c32ad4fe59e0059bee3a0df54~mv2.png",
"sprite":"https://static.wixstatic.com/media/5f9784_fd7c4d8a20fe419db75443b3ab10d89d~mv2.png",
"coca cola":"https://static.wixstatic.com/media/5f9784_f3fd60f9d4cf434484aa4563377577fd~mv2.png",
"fanta":"https://static.wixstatic.com/media/5f9784_66c44ea812e14690ad4709230e5b32ad~mv2.png",
"cappy meyve suyu":"https://static.wixstatic.com/media/5f9784_356e27e72b6d4c7bb4fb898aa626db4b~mv2.png",
"fuse tea":"https://static.wixstatic.com/media/5f9784_7ade8b1189da4c89a533b969f62277e5~mv2.png",
"redbull":"https://static.wixstatic.com/media/5f9784_27f512ad91ab472f8cce4141cc3d9392~mv2.jpg",
"taze portakal suyu":"https://static.wixstatic.com/media/5f9784_283b065481f6438c918a79566465c4ad~mv2.png",
"s.pellegrino":"/images/menu/soft/St.Pellegrino.webp","soda":"/images/menu/soft/Soda.webp","uludağ soda":"/images/menu/soft/uludag.webp","tiramisu":"/images/menu/tatli/Tiramisu-edited.webp",
  "katmer":"/images/menu/tatli/katmer.jpeg",
  "cheddar fume":"/images/menu/sicak/cheddar-f├╝me.webp",
  "spagetti 200 gr":"/images/menu/sicak/spaketti.webp",
  "kasap kofte":"/images/menu/kofte/kasap-k├Âfte-edited.webp"
,
  "olmeca":"/images/menu/alkollu/tekila/olmeca-blanco.webp",
  "smirnoff red":"/images/menu/alkollu/votka/smirnof-edited-2.webp",
  "absolut":"/images/menu/alkollu/votka/99033-absolut-vodka-1L-40-vol.webp",
  "belvedere":"https://static.wixstatic.com/media/5f9784_b28bd918a9ec40aa8945847245151c4d~mv2.png",
  "beefeater":"/images/menu/alkollu/cin/gin-beefeater-1l.webp",
  "gordon's":"/images/menu/alkollu/cin/gordon-s-70-cl.webp",
  "campari":"/images/menu/alkollu/likor/campari.webp",
  "baileys":"/images/menu/alkollu/likor/baileys-original-irish-cream-1.webp",
  "grappa":"/images/menu/alkollu/likor/ci-candolini-grappa-bianca-29531b1bfcfc19ad.webp",
  "limoncello":"/images/menu/alkollu/likor/il-tramonto-limoncello-750ml.webp",
  "miller 33 cl":"/images/menu/alkollu/bira/miller.webp",
  "efes pilsen 33 cl":"/images/menu/alkollu/bira/efes.webp",
  "efes malt 50 cl":"/images/menu/alkollu/bira/efes-malt.webp",
  "bomonti filtresiz 50 cl":"/images/menu/alkollu/bira/bomonti.webp",
  "corona 33 cl":"/images/menu/alkollu/bira/CORONA.webp",
  "beylerbeyi gobek":"/images/menu/alkollu/raki/beylerbeyi-gobek-70cl-edited.webp",
  "yeni raki":"/images/menu/alkollu/raki/yeni-rak─▒.webp",
  "yeni raki- ala":"/images/menu/alkollu/raki/ala.webp",
  "tekirdag rakisi":"/images/menu/alkollu/raki/tekirdas─ş.webp",
  "tekirdag rakisi gold":"/images/menu/alkollu/raki/gold.webp",
  "gold efe raki":"/images/menu/alkollu/raki/goldefe.webp",
  "beylerbeyi terra gold":"/images/menu/alkollu/raki/TERRA.webp",
  "beylerbeyi mavi":"/images/menu/alkollu/raki/BEYLERBEYI-RAKI-MAVI-70CL.webp",
  "klup raki":"/images/menu/alkollu/raki/Kulup-Raki-700ml-800x1000-edited.webp",
  "sari zeybek 3 mese 70 cl":"/images/menu/alkollu/raki/sari-zeybek-3-me┼şe-edited.webp",
  "mercan 70 cl":"/images/menu/alkollu/raki/mercan.webp",
  "chivas regal 12. y. o":"/images/menu/viski/chivas-12-01.webp",
  "chivas regal 18. y. o":"/images/menu/viski/chivas-regal-18yr-750ml.webp",
  "johnnie walker black label":"/images/menu/viski/32699-0w600h600-Johnnie-Walker-Black-Label-Whisky-Sample-Bottle.webp",
  "bulleit bourbon":"/images/menu/viski/Bulleit-Bourbon-Frontier-Whiskey.webp",
  "jack daniels tennessee":"/images/menu/viski/ci-jack-daniels-old-no-7-92707d5e737cf4ac.webp",
  "glenmorangie 10 y.o. %40":"/images/menu/viski/glenmorangie-10-yo-original-highland-single-malt-scotch-whisky-70cl-40-abv-temp.webp",
  "talisker 10. y.o. %45,8":"/images/menu/viski/Talisker-10-Year-Scotch-200ML-2.webp",
  "the glenlivet 18. y.o. %43":"/images/menu/viski/glenlivet-single-malt-scotch-18-yr-speyside.webp",
  "the macallan 12 y.o. sherry oak cask":"/images/menu/viski/The-Macallan-12-year.webp",
  "suvla / cabarnet sauvignon-merlot":"/images/menu/sarap/suvla-cabernet-sauvignon-merlot-933514-1200x1200.webp",
  "suvla / okuzgozu/bogazkere":"/images/menu/sarap/suvla-okuzgozu-440905-600.webp",
  "kavaklidere / egeo merlot":"/images/menu/sarap/egeo-merlot.webp",
  "oguz vigna nord":"/images/menu/sarap/CALROSSO.webp",
  "consensus / shiraz & cabernet sauvignon & merlot":"/images/menu/sarap/LA-CONSENSUS-KIRMIZI-2015-IZMIR.webp",
  "ament blend":"/images/menu/sarap/PORTA-CAELI-AMENT-BLEND-2019-ECEABAT-edited.webp",
  "yedi bilgeler pythgoras":"/images/menu/sarap/Yedi-Bilgeler-Pythagoras-kirmizi-sarap.webp",
  "chamlija nevi sahsina munasir":"/images/menu/sarap/chamlija-nevi-sahsina-munhasir-855975-ca91d839-5157-45bc-9858-29baff7a758b.webp",
  "kavaklidere / sultaniye y.tatli":"/images/menu/sarap/yaritatli-sultaniye.webp",
  "tomassi soave classico":"/images/menu/sarap/Tomassi-Soave.webp",
  "chablis le finage aoc":"/images/menu/sarap/chablis.webp",
  "roc de i'abbaye sancerre blanc":"/images/menu/sarap/sancerre.webp",
  "yedi bilgeler khilon":"/images/menu/sarap/7-bilgeler-khilon-premium-rotwein.webp",
  "yedi bilgeler anaxagoras":"/images/menu/sarap/yedi-bilgeler-anaxagoras-chardonnay-980740.webp",
  "chamlija quartz fume":"/images/menu/sarap/chamlija-quartz-fume.webp",
  "kavaklidere / ancyra blush":"/images/menu/sarap/ancyra-blush.webp",
  "bodvar cotes de pronence":"/images/menu/sarap/BODVAR.webp",
  "arjantin / kaiken reserva malbec":"/images/menu/sarap/kaiken-malbec-reserva-2016-mendoza-argentina.webp",
  "fransa / aoc, bourgogne, jaffelin pinot noir":"/images/menu/sarap/jaffelin-vin-de-france-pinot-noir-scaled-510x631.webp",
  "muga reserva":"/images/menu/sarap/muga.webp",
  "marchesi di barolo & serrragilli barbaresco":"/images/menu/sarap/serragrilli-barbaresco.webp",
  "tomassi amarone della valpolicella classico":"/images/menu/sarap/Tommasi-Amarone-Classico-Since1902.webp",
  "suvla / chardonnay":"/images/menu/sarap/SUVLA.webp",
  "suvla sauvignon blanc & semillon":"/images/menu/sarap/SUVLA.webp",
  "sartori pinot grigio":"/images/menu/sarap/BLUS.webp"
 };return images[n]||Object.entries(images).find(([key])=>imageKey(key)===n)?.[1]||null;
};
const itemImage=(i:I)=>i.image_path?process.env.NEXT_PUBLIC_SUPABASE_URL+"/storage/v1/object/public/menu-images/"+i.image_path:localImage(i.name_tr);
const money=(v:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(v));export default async function Page({searchParams}:{searchParams:Promise<{menu?:string}>}){const q=await searchParams,db=await createServerSupabase();const [{data:cs},{data:ss},{data:ii},{data:vv}]=await Promise.all([db.from("menu_categories").select("*").eq("is_active",true).order("sort_order"),db.from("menu_sections").select("*").eq("is_active",true).order("sort_order"),db.from("menu_items").select("*").eq("is_active",true).order("sort_order"),db.from("menu_item_variants").select("*").eq("is_active",true).order("sort_order")]);const cats=(cs||[]) as C[],active=cats.find(c=>c.slug===q.menu)||cats[0],secs=((ss||[]) as S[]).filter(s=>s.category_id===active?.id),items=(ii||[]) as I[],vars=(vv||[]) as V[],pick=(o:any,k:string)=>o[k+"_en"]||o[k+"_tr"];return <main className="menuPage"><section className="menuTop"><h1>Menu</h1><nav className="menuTabs">{cats.map(c=><a className={active?.id===c.id?"active":""} href={"/en/menu?menu="+c.slug} key={c.id}>{pick(c,"title")}</a>)}</nav></section><section className="wixMenu"><h2 className="menuCategoryTitle">{active&&pick(active,"title")}</h2>{secs.map(s=><section className="menuSection" key={s.id}><h2>{pick(s,"title")}</h2><div className="sectionRule"/>{items.filter(i=>i.section_id===s.id).map(i=>{const vs=vars.filter(v=>v.item_id===i.id);return <article className="dish" key={i.id}><div className="dishMedia">{itemImage(i)&&<img className="menuItemImage" src={itemImage(i)!} alt={pick(i,"name")}/>}</div><div className="dishCopy"><div className="dishTitleRow"><h3>{pick(i,"name")}</h3><span className="dishDots"/><div className="dishPrice">{vs.length?vs.map(v=><div className="variant" key={v.id}><span>{v.label_tr}</span><strong>{money(v.price)}</strong></div>):<strong>{money(i.price)}</strong>}</div></div>{pick(i,"description")&&<p>{pick(i,"description")}</p>}{i.tags?.length>0&&<p className="dishTags">{i.tags.join(" · ")}</p>}</div></article>})}</section>)}</section></main>}